### PR TITLE
Open closed full states

### PR DESCRIPTION
**Pull request by hardaker**
This implements the open/closed/full states and adds some buttons to the logged-in match page for quick toggling.

related: #27

### CODE REVIEW

**Comment by rjsparks** [comment]
closing this as obe

**Comment by hardaker** [comment]
it's actually not OBE, but the needed feature can wait for the larger rewrite and integration with datatracker.

this patch: disallow registrations between IETFs

the patch you just approved: allow guides to say "I'm always available" or "just this one time"

**Comment by rjsparks** [comment]
Right - sorry - let me try to do this differently then.

Capturing a sketch of offline conversations here: This PR mutates state with GETs. I'm moving it from closed to draft so it is easier to find as input to addressing #27 in the next rewrite.

**Comment by hardaker** [comment]
We'll give up on this one -- we have sort of changed our approach anyway.

**Pull request closed without merging**
